#!/usr/bin/env bash
# Summary: Show the current R version(s) and its origin
#
# Shows the currently selected R version(s) and how it was
# selected. To obtain only the version string, use `renv
# version-name'.

set -e
[ -n "$RENV_DEBUG" ] && set -x

exitcode=0
OLDIFS="$IFS"
IFS=: RENV_VERSION_NAMES=($(renv-version-name)) || exitcode=$?
IFS="$OLDIFS"

for RENV_VERSION_NAME in "${RENV_VERSION_NAMES[@]}"; do
  echo "$RENV_VERSION_NAME (set by $(renv-version-origin))"
done

exit $exitcode
