#!/usr/bin/env bash
# Summary: Installs all packages specified in renv.lock.
# Usage: renv sync
#

set -e
[ -n "$RENV_DEBUG" ] && set -x

if [ ! -f "renv.lock" ]; then
    echo "ERROR: renv.lock not found!"
else
    found_R=false
    # Get the first "Version:" after the "R:" tag.
    # TODO: Must be improved! Parse the JSON.
    while IFS= read -r line; do
        found_R=found_R || [[ "$line" == *'"R"'* ]]
        if [[ $found_R && "$line" == *'"Version"'* ]]; then
            break;
        fi
    done < "renv.lock"
    r_version=$(echo "$line" | cut -d'"' -f4)
    if [ -d "$RENV_ROOT/versions/$r_version" ]; then 
        echo $r_version > .R-version
        R -e 'install.packages("renv", repos = "https://cloud.r-project.org"); renv::restore()'
    else
        echo "ERROR: required R version not installed, or malformed renv.lock"
    fi
fi
