#!/usr/bin/env bash
# Usage: renv version-file-write <file> <version>

set -e
[ -n "$RENV_DEBUG" ] && set -x

RENV_VERSION_FILE="$1"
shift || true
versions=("$@")

if [ -z "$versions" ] || [ -z "$RENV_VERSION_FILE" ]; then
  renv-help --usage version-file-write >&2
  exit 1
fi

# Make sure the specified version is installed.
renv-prefix "${versions[@]}" >/dev/null

# Write the version out to disk.
# Create an empty file. Using "rm" might cause a permission error.
> "$RENV_VERSION_FILE"
for version in "${versions[@]}"; do
  echo "$version" >> "$RENV_VERSION_FILE"
done
