#!/usr/bin/env bash
set -e
[ -n "$RENV_DEBUG" ] && set -x

# Provide renv completions
if [ "$1" = "--complete" ]; then
  exec renv-rehash --complete
fi

shell="$(basename "${RENV_SHELL:-$SHELL}")"

# When renv shell integration is enabled, delegate to renv-rehash,
# then tell the shell to empty its command lookup cache.
renv-rehash

case "$shell" in
fish )
  # no rehash support
  ;;
* )
  echo "hash -r 2>/dev/null || true"
  ;;
esac
