#!/usr/bin/env bash
# Summary: Installs all packages specified in `renv.lock` file
# Usage: renv sync
#

set -e
[ -n "$RENV_DEBUG" ] && set -x

if [ ! -f "renv.lock" ]; then
    echo "ERROR: renv.lock not found!"
else
    found_R=false
    # Get the first "Version:" after the "R:" tag.
    # TODO: Must be improved! Parse the JSON.
    while IFS= read -r line; do
        found_R=found_R || [[ "$line" == *'"R"'* ]]
        if [[ $found_R && "$line" == *'"Version"'* ]]; then
            break;
        fi
    done < "renv.lock"
    r_version=$(echo "$line" | cut -d'"' -f4)
    if [ -d "$RENV_ROOT/versions/$r_version" ]; then
        # If R version is installed, set it as default for this project, and install renv packages.
        echo $r_version > .R-version
        R -e 'install.packages("renv", repos = "https://cloud.r-project.org"); renv::restore()'
    else
        # Ask if R version should be installed.
        echo "renv.lock file requires R "$r_version" to be installed."
        read -p "Do you want to install it? [Y/n] " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Nn]$ ]]; then
            echo "ERROR: required R version not installed, or malformed renv.lock"
            exit 1;
        fi
        # Install required R version, set it as default for this project, and install renv packages.
        renv install $r_version
        echo $r_version > .R-version
        R -e 'install.packages("renv", repos = "https://cloud.r-project.org"); renv::restore()'
    fi
fi
