#!/usr/bin/env bash
# Usage: renv completions <command> [arg1 arg2...]

set -e
[ -n "$RENV_DEBUG" ] && set -x

COMMAND="$1"
if [ -z "$COMMAND" ]; then
  renv-help --usage completions >&2
  exit 1
fi

# Provide renv completions
if [ "$COMMAND" = "--complete" ]; then
  exec renv-commands
fi

COMMAND_PATH="$(command -v "renv-$COMMAND" || command -v "renv-sh-$COMMAND")"

# --help is provided automatically
echo --help

if grep -iE "^([#%]|--|//) provide renv completions" "$COMMAND_PATH" >/dev/null; then
  shift
  exec "$COMMAND_PATH" --complete "$@"
fi
