#!/usr/bin/env bash
# Summary: Explain how the current R version is set
set -e
[ -n "$RENV_DEBUG" ] && set -x

unset RENV_VERSION_ORIGIN

OLDIFS="$IFS"
IFS=$'\n' scripts=(`renv-hooks version-origin`)
IFS="$OLDIFS"
for script in "${scripts[@]}"; do
  source "$script"
done

if [ -n "$RENV_VERSION_ORIGIN" ]; then
  echo "$RENV_VERSION_ORIGIN"
elif [ -n "$RENV_VERSION" ]; then
  echo "RENV_VERSION environment variable"
else
  renv-version-file
fi
